# Site settings
title: Clara Rules
email: rbrush@gmail.com

description: > # this means to ignore newlines until "baseurl:"
  Forward-chaining rules in Clojure.
baseurl: "" # the subpath of your site, e.g. /blog/
## url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
twitter_username: ryanbrush
github_username:  rbrush

collections:
  docs:
    output: true

# Build settings
markdown: kramdown

# Clara version and documentation location.
clara_version: 0.9.0
javadoc: /apidocs/0.9.0/java/
clojuredoc: /apidocs/0.9.0/clojure/
